service: deployment-example-sls
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: handlers/posts.handler
    events:
      - http:
          method: GET
          path: /

# only include the Prisma binary required on AWS Lambda while packaging
package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
  
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: npm
    includeModules:
      forceExclude:
        - aws-sdk
      # forceInclude:
        # - '.prisma'
    packagerOptions:
      scripts:
        - npx prisma generate
