service: deployment-example-sls
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: handlers/posts.handler
    events:
      - http:
          method: GET
          path: /

package:
  individually: true
  
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: npm
    includeModules: true
